hpc <- read.delim("household_power_consumption.txt", sep = ";", na.strings = "?", colClasses = c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
hpc <- subset(hpc, (Date == "1/2/2007") | (Date == "2/2/2007"))
png(filename = "plot1.png")
par(bg = "transparent")
hist(hpc$Global_active_power, main = "Global Active Power", col = "red", xlab = "Global Active Power (kilowatts)")
dev.off()